kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sonarqube-fast-claim
  labels:
    app: sonarqube
spec:
  storageClassName: ssd-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

