apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarqube-fast-pv
  labels:
    app: sonarqube
spec:
  storageClassName: ssd-retain
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: sonarqube-fast-claim
  gcePersistentDisk:
    pdName: gke-gocd-cluster-f1dce-pvc-e1370d93-208a-4fe2-96e3-92258855564e
    fsType: ext4